name: supervecina
version: 1.1.52+192
description: Cross platform mobile Ethereum wallet.
environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  carrier_info: ^2.0.4
  flutter_localized_locales: ^2.0.3
  app_tracking_transparency: ^2.0.1
  responsive_framework: ^0.1.5
  flutter_web_browser: ^0.16.0
  modal_bottom_sheet: ^2.0.0
  grouped_list: ^4.0.0
  number_display: ^3.0.0
  auto_size_text_field: ^1.0.1
  fl_chart: ^0.41.0
  pin_code_fields: ^7.3.0
  flex_color_scheme: ^4.2.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  dio: ^4.0.4
  font_awesome_flutter: ^9.2.0
  flushbar:
    git:
      url: git://github.com/prasadsunny1/flushbar
      ref: master
  flutter_platform_widgets: ^1.12.1
  enum_to_string: ^2.0.1
  local_auth: ^1.1.10
  auto_size_text: ^3.0.0
  webview_flutter: ^3.0.0
  phone_number: ^0.12.0+1
  cached_network_image: ^3.2.0
  auto_route: ^3.2.2
  url_launcher: ^6.0.18
  google_maps_flutter: ^2.1.1
  equatable: ^2.0.3
  package_info: ^2.0.2
  share: ^2.0.4
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^5.0.2
  flutter_redux: ^0.8.2
  flutter_dotenv: ^5.0.2
  redux_thunk: ^0.4.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  country_code_picker: ^2.0.2
  wallet_core:
    git:
      url: https://github.com/fuseio/wallet_core.git
      ref: master
  scan: ^1.6.0
  contacts_service: ^0.6.3
  permission_handler: ^8.3.0
  qr_flutter: ^4.0.0
  logger: ^1.1.0
  json_annotation: ^4.3.0
  flare_flutter: ^3.0.2
  decimal: ^2.1.0
  firebase_remote_config: ^1.0.4
  firebase_messaging: ^11.2.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  ethereum_addresses: ^1.0.2
  sentry_flutter: ^6.2.2
  image_picker: ^0.8.4+4
  flutter_cupertino_localizations: ^1.0.1
  flutter_udid: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  freezed: ^1.1.1
  lint: ^1.8.2
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.1
  flutter_native_splash: ^1.3.3
  dependency_validator: ^3.1.2
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
    - family: Eras
      fonts:
        - asset: assets/fonts/eras_bd.ttf
          weight: 300
        - asset: assets/fonts/eras_bd.ttf
          weight: 400
        - asset: assets/fonts/eras_bd.ttf
          weight: 600
        - asset: assets/fonts/eras_bold.ttf
          weight: 700
        - asset: assets/fonts/eras_bold.ttf
          weight: 800
        - asset: assets/fonts/eras_bold.ttf
          weight: 900
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en_US
  localizely:
    project_id: 059fb9dd-4449-4e79-92ef-4d786cf38e5a
    download_empty_as: main
